version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: mydb
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myappdb
    ports:
      - "5432:5432"
    volumes:
      - my-app-db-data:/var/lib/postgresql/data

  web:
    image: jackydo2k5/jackywebapp:final-version-2025b   # replace with your pushed Tomcat image
    container_name: mytomcat
    restart: always
    depends_on:
      - db
    ports:
      - "8084:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: myappdb

volumes:
  my-app-db-data:
